version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: rentx_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker123
      - POSTGRES_DB=rentx_database
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx_app
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_ignite
    depends_on:
      - database_ignite

volumes:
  pgdata:
    driver: local